### ISSUE TITLE
What do you need?

### ISSUE THREAD

**Issue by MemeHoovy** [MMbay64/Parasoft#1]
you invited me to the repo, what do you need?

**Comment by MMbay64** [comment]
I little help,it's ok if you don't wanna work

**Comment by MemeHoovy** [comment]
I will, but I'm working on like now 20 different projects, so I might not be pretty active though

**Comment by MMbay64** [comment]
Oh wow 😧 ok

**Comment by MMbay64** [comment]
> I will, but I'm working on like now 20 different projects, so I might not be pretty active though

hey come check out Discord with me https://discord.gg/mnrU3MBk

**Comment by MemeHoovy** [comment]
alright
